spring.application.name=Projeto

#banco de dados (PostgreSQL Externo - com suporte a Variáveis de Ambiente)
spring.datasource.url=${DB_URL:jdbc:postgresql://192.168.1.244:5432/base_estudos?currentSchema=bd_rsc_poo}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.api-docs.path=/v3/api-docs 

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=bd_rsc_poo
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

spring.security.user.name=admin
spring.security.user.password=12